# Site settings
title: "kkyon"
description: "Minimalist Jekyll theme for documentation site"
baseurl: "/" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: ""
author: "kkyon"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
repository: kkyon/botflow
google_analytics: UA-125816898-1
disqus_shortname: kkyon

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
